# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: 'true'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: archlint @self
        run: npm run archlint
      - name: Write Version to package.json
        run: sed -i "s/0.0.0-SNAPSHOT/${{ github.ref_name }}/" package.json && echo "Version ${{github.ref_name}}"
        if: startsWith(github.event.ref, 'refs/tags/')
      - name: Configure Token
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: npm publish
        if: startsWith(github.event.ref, 'refs/tags/')
